### PR TITLE
add run_opts/4 fork_opts/4 and actor_opts/4 for controlling pipe attributes

### PR DESCRIPTION
**Pull request by johnfoconnor**
you can choose between inproc and ipc as well as change the type or name of the socket

### CODE REVIEW

**Comment by moteus** [comment]
Thanks. I think do it by self because there problem using `inproc` sockets with external event loops(e.g. libuv). 

But I have some suggestion.

To support tcp transport we need to use unique port for each socket pair.
We can use something like
```Lua
pipe:bind(pipe_endpoint)
...
return pipe, pipe:last_endpoint()
```
and use it as `{endpoint = "tcp://127.0.0.1:*"}`

Problem is that ZMQ_LAST_ENDPOINT documented only for tcp/ipc but not for inproc.
But on my wndows (ZMQ 4.2.0) system it works also with inproc.
Also it returns `\0` at the end of string (needs to check with other options)

Because of that I suggest
For inproc/ipc use `pipe_endpoint` as before
For TCP with explicity setted `name` use `last_endpoint` option (with removing `\0` if needed)
For TCP without name setted we can `bind('tcp://127.0.0.1:*')` and use `last_endpoint` (need to test with older versions) or we can use  `bind_to_random_port('tcp://127.0.0.1')` function and generate `pipe_endpoint` byself.

Also please add test to this. You can use `test_threads_opt.lua` with tcp protocol.

**Comment by johnfoconnor** [comment]
looks like ZMQ_LAST_ENDPOINT is defined for for IPC and TCP on ZMQ API >= 3.2
http://api.zeromq.org/3-2:zmq-getsockopt

I will attempt to implement your suggestions

**Comment by moteus** [comment]
I have question.
Why we need `type` option?
Child thread creates `PAIR` and connect it to non PAIR socket is not defined.
May be remove this? If you have some use case may be create new PR where you also pass socket type child thread. But really I have no idea why you need this.

Also please do not update test. Just copy file with new name and update it.

> looks like ZMQ_LAST_ENDPOINT is defined for for IPC and TCP on ZMQ API >= 3.2

Yes. It there since ZMQ 3.2.0
I think it is ok do not support ZMQ 3.1.0 in this case

**Comment by johnfoconnor** [comment]
the `type` option is there so eventually you dont have to have an exclusive pair. For instance, what if i want to spawn a child with REP and connect a DEALER to the endpoint?

we would have to change fork_starter a bit since it sets up the other pipe automatically right now. I will remove this `type` option for now and leave it for future discussion

**Comment by moteus** [comment]
May be we can use one option table?

```Lua
zthread.xfork{function(pipe)
...
end; protocol = 'tcp'}
```
In this case we can not produce 3 new functions

**Comment by johnfoconnor** [comment]
are you saying you want to combine threading options with the pipe options?

**Comment by moteus** [comment]
>are you saying you want to combine threading options with the pipe options?

Why not? For me as for user it is not just thread options but named options for this function (actor/fork/run).

**Comment by johnfoconnor** [comment]
yeah we can do that. I was wary of combining the options in case there was a naming conflict but it's not that important. it's probably easier for the user to have a single opts table

**Comment by moteus** [comment]
I have no strong opinion about name.
We configure `endpoint` argument for `pipe` object. So for me `pipe` is more obviuse name.
But I just merge this and think more about this.

**Pull request merged**
